CREATE TABLE IF NOT EXISTS tags (
    id SERIAL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    created_by TEXT,
    status TEXT
);
